{{- $name := include "sh360-web.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "sh360-web.name" . }}
    chart: {{ template "sh360-web.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
 ApplicationInsights__InstrumentationKey:  ID_APP_INSIGHTS
