-{{$name := include "sh360-postgres.fullname" . }}
-{{$fullname := printf "%s-%s" "tasks" $name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ template "sh360-postgres.name" . }}
    chart: {{ template "sh360-postgres.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "sh360-postgres.name" . }}
    release: {{ .Release.Name }}
    db: tasks
